from typing import Protocol, List
from domain.entities.job import Job

class SchedulerPort(Protocol):
    def start(self) -> None: ...
    def add_job(self, job: Job) -> None: ...
    def remove_job(self, job_id: str) -> None: ...
    def resume_job(self, job_id: str) -> None: ...
    def trigger_job(self, job_id: str) -> None: ...
    def get_job(self, job_id: str) -> Job: ...
    def get_all_jobs(self) -> List[str]: ...
    def print_all_jobs(self) -> None: ...
