apiVersion: v1
kind: Service
metadata:
  name: monstrino-ui
  namespace: monstrino-test
  labels: 
    project: monstrino
    component: ui
spec:
  type: ClusterIP
  selector:
    project: monstrino
    component: ui
  ports:
  - name: http
    port: 80
    targetPort: ui-http

