from infrastructure.interfaces_impl.google_interface import GoogleInterfaceImpl
from infrastructure.interfaces_impl.scheduler_interface_impl import SchedulerInterfaceImpl
from infrastructure.interfaces_impl.searchapi_interface_impl import SearchAPIInterfaceImpl
from infrastructure.interfaces_impl.website_bricklick_interface import WebsiteBricklinkInterface
from infrastructure.interfaces_impl.website_brickset_interface import WebsiteBricksetInterfaceImpl
from infrastructure.interfaces_impl.website_capi_cap_interface import WebsiteCapiCapInterface
from infrastructure.interfaces_impl.website_kostickyshop_interface import WebsiteKostickyshopInterface
from infrastructure.interfaces_impl.website_lego_interface import WebsiteLegoInterfaceImpl
from infrastructure.interfaces_impl.website_museum_of_bricks_interface import WebsiteMuseumOfBricksInterfaceImpl
from infrastructure.interfaces_impl.website_sparkys_interface import WebsiteSparkysInterface

website_lego_interface = WebsiteLegoInterfaceImpl()
website_bricklink_interface = WebsiteBricklinkInterface()
website_capi_cap_interface = WebsiteCapiCapInterface()
website_museum_of_bricks_interface = WebsiteMuseumOfBricksInterfaceImpl()
website_sparkys_interface = WebsiteSparkysInterface()
website_kostickyshop_interface = WebsiteKostickyshopInterface()
website_brickset_interface = WebsiteBricksetInterfaceImpl()

scheduler_interface = SchedulerInterfaceImpl()


google_interface = GoogleInterfaceImpl()
search_api_interface = SearchAPIInterfaceImpl()