from dataclasses import dataclass
from application.repositories.release_image_repository import ReleaseImagesRepository
from application.repositories.release_relation_link_repository import ReleaseRelationsRepository
from application.repositories.dolls_release_repository import DollsReleasesRepository
from application.repositories.dolls_series_repository import DollsSeriesRepository
from application.repositories.dolls_types_repository import DollsTypesRepository
from application.repositories.original_characters_repository import OriginalCharactersRepository
from application.repositories.release_character_link_repository import ReleaseCharactersRepository


@dataclass
class Repositories:
    dolls_series: DollsSeriesRepository
    dolls_types: DollsTypesRepository
    dolls_release: DollsReleasesRepository
    release_image: ReleaseImagesRepository
    release_relation_link: ReleaseRelationsRepository
    release_character_link: ReleaseCharactersRepository
    original_characters: OriginalCharactersRepository
