from typing import Protocol, AsyncGenerator

from monstrino_models.dto import ParsedCharacter


class ParseCharacterPort(Protocol):
    async def parse(self): ...

    def parse_ghouls(self, batch_size: int, limit: int) -> AsyncGenerator[list[ParsedCharacter]]: ...
    def parse_mansters(self, batch_size: int, limit: int) -> AsyncGenerator[list[ParsedCharacter]]: ...

    # async def parse(self, ): ...