from typing import Protocol, List

from apscheduler.job import Job


class SchedulerPort(Protocol):
    async def start(self) -> None: ...
    async def add_job(self, job: Job) -> None: ...
    async def remove_job(self, job_id: str) -> None: ...
    async def get_all_jobs(self) -> List[str]: ...