from typing import Protocol, AsyncGenerator

from domain.entities.parsed_character_dto import ParsedCharacterDTO


class ParseCharactersPort(Protocol):
    async def parse(self): ...

    async def parse_ghouls(self) -> AsyncGenerator[list[ParsedCharacterDTO]]: ...
    async def parse_mansters(self) -> AsyncGenerator[list[ParsedCharacterDTO]]: ...

    # async def parse(self, ): ...